name: PR to main
on: 
  pull_request:
    branches:
      - main
jobs:
  terraform:
    name: terraform CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      TF_VAR_iac_github_token: ${{secrets.IAC_GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: |
          terraform init

      - name: Terraform Plan
        run: |
          terraform plan -plan.out
          terraform show -no-color plan.out > plan.txt

      - name: Extract summary
        id: summary
        run: |
          SUMMARY=$(grep '^Plan:' plan.txt)
          echo "summary=$SUMMARY" >> $GITHUB_OUTPUT
          
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment "$PR_URL" --body "🧪 Terraform Plan Summary: ${{ steps.summary.outputs.summary }}"